#!/usr/bin/env python3
"""
Fraud Detection Module
Contains all fraud detection services and models
"""

from .investment_models import *
from .investment_fraud_service import InvestmentFraudDetectionService
from .ml_models import *
from .ml_service import MLService
from .graph_models import *
from .gnn_service import GNNService
from .fraud_tools_models import *
from .fraud_tools_service import FraudTools
from .conversation_models import *
from .conversation_service import FraudConversationService
from .advanced_algorithms_models import *
from .advanced_algorithms_service import AdvancedFraudAlgorithms
from .data_stream_models import *
from .feature_vector_models import *
from .performance_monitoring_models import *
from .configuration_models import *
from .configuration_manager import ConfigurationManager, ConfigurationLoader, get_config_manager, load_config, get_config
from .security_models import *
from .jwt_service import JWTService, PasswordService
from .authentication_service import AuthenticationService
from .authorization_service import AuthorizationService
from .security_middleware import SecurityMiddleware, get_current_user, require_auth
from .database_service import DatabaseService, database_service
from .data_quality_service import DataQualityService, data_quality_service
from .ml_training_pipeline import MLTrainingPipeline, ml_training_pipeline
from .feature_engineering_service import FeatureEngineeringService, feature_engineering_service
from .performance_service import PerformanceMonitor, PerformanceOptimizer, performance_monitor, performance_monitor_instance, performance_optimizer
from .performance_models import *
from .rules_engine_models import *
from .static_rules import IRule, get_default_static_rules
from .rules_engine_service import AdvancedRulesEngine, RuleManagementService, rules_engine
from .messaging_models import *
from .service_bus_publisher import ServiceBusPublisher
from .service_bus_subscriber import ServiceBusSubscriber
from .event_hubs_publisher import EventHubsPublisher
from .messaging_service import MessagingService, get_messaging_service
from .customer_portal_models import *
from .customer_portal_service import CustomerPortalService, customer_portal_service

__all__ = [
    'InvestmentFraudDetectionService',
    'MLService',
    'GNNService',
    'FraudTools',
    'FraudConversationService',
    'AdvancedFraudAlgorithms',
    'InvestmentPortfolio',
    'InvestmentTransaction',
    'InvestmentTransactionRequest',
    'InvestmentRiskAssessment',
    'InvestmentValidationResult',
    'TradingPattern',
    'RiskFactor',
    'RiskLevel',
    'Severity',
    'TransactionType',
    'AssetType',
    'InvestmentFraudAlert',
    'MarketDataPoint',
    'PerformanceData',
    'SectorAllocation',
    'PortfolioAnalysis',
    'InvestmentSummaryDto',
    'InvestmentRecommendationDto',
    'MarketNews',
    'ExternalAccountLink',
    'InvestmentPlatform',
    'MarketVolatilityData',
    'MarketDataDto',
    'MLModel',
    'ModelType',
    'ModelStatus',
    'EnsembleConfig',
    'EnsembleMethod',
    'ModelPredictionRequest',
    'ModelPredictionResponse',
    'ModelTrainingConfig',
    'ModelTrainingResult',
    'ModelMetrics',
    'ModelVersion',
    'ModelDriftResult',
    'ModelFeedback',
    'ModelPerformanceMonitor',
    'ModelRetrainingJob',
    'ConfusionMatrix',
    'ModelPerformance',
    'FraudDetectionGraph',
    'GraphNode',
    'GraphEdge',
    'GraphMetadata',
    'GraphStatistics',
    'GraphConfiguration',
    'FraudRing',
    'GraphCommunity',
    'FraudRingResult',
    'GraphAnalysisResult',
    'GNNModelConfig',
    'NodeType',
    'EdgeType',
    'GraphNodeType',
    'GraphEdgeType',
    'CommunityType',
    'GraphStatus',
    'GraphNodeMetadata',
    'GraphEdgeMetadata',
    'FraudRiskScore',
    'FraudAssessment',
    'FraudRiskAssessment',
    'Transaction',
    'VelocityAnalysis',
    'FrequencyAnalysis',
    'AmountPatternAnalysis',
    'MerchantRiskProfile',
    'LocationRiskProfile',
    'TimeRiskProfile',
    'FraudAlert',
    'FraudFeedback',
    'CounterfactualResult',
    'TransferRequest',
    'PaymentRequest',
    'CardOperationRequest',
    'RecommendedAction',
    'FraudChatRequest',
    'FraudChatResponse',
    'UserContext',
    'ConversationContext',
    'ConversationMessage',
    'FraudAnalysisRequest',
    'FraudAnalysisResult',
    'IntelligentFraudResponse',
    'AISettings',
    'ChatRequestDto',
    'ChatResponseDto',
    'TokenUsageStats',
    'ChatOption',
    'VerificationQuestion',
    'Platform',
    'PlatformRiskWeights',
    'BehavioralProfile',
    'DeviceProfile',
    'NetworkProfile',
    'VelocityProfile',
    'TransactionData',
    'ComprehensiveRiskAnalysis',
    'FraudPattern',
    'AdvancedAnalyticsData',
    # Data Stream Models
    'DataType',
    'DataStream',
    'FraudAnalysis',
    'AppMessage',
    'DataStreamSettings',
    'DataStreamStats',
    'DataStreamAnalysisRequest',
    'DataStreamAnalysisResponse',
    'DataStreamBatchRequest',
    'DataStreamBatchResponse',
    # Feature Vector Models
    'FeatureVectorStatus',
    'FeatureDataType',
    'FeatureImportance',
    'FeatureSource',
    'NumericFeatures',
    'CategoricalFeatures',
    'BinaryFeatures',
    'TimeSeriesFeatures',
    'FeatureVector',
    'FeatureSetVersion',
    'FeatureVectorMetadata',
    'FeatureVectorValidationResult',
    'CreateFeatureVectorRequest',
    'CreateFeatureVectorResponse',
    'UpdateFeatureVectorRequest',
    'QueryFeatureVectorsRequest',
    'QueryFeatureVectorsResponse',
    'ValidateFeatureVectorRequest',
    'MigrateFeatureVectorsRequest',
    'MigrateFeatureVectorsResponse',
    # Performance Monitoring Models
    'AlertSeverity',
    'AlertType',
    'DriftType',
    'DriftSeverity',
    'TrendDirection',
    'AnomalyType',
    'AnomalyImpact',
    'ReportType',
    'ExportFormat',
    'ExportScope',
    'ExportStatus',
    'EnhancedModelPerformance',
    'PerformanceAlert',
    'PerformanceDriftResult',
    'PerformanceTrendPoint',
    'PerformanceDashboardData',
    'PerformanceAnomaly',
    'PerformanceTrendAnalysis',
    'PerformanceReport',
    'PerformanceExportRequest',
    'PerformanceExportResult',
    # Configuration Models
    'ConfigurationManager',
    'ConfigurationLoader',
    'get_config_manager',
    'load_config',
    'get_config',
    'FraudDetectionAgentConfig',
    'DatabaseSettings',
    'JwtSettings',
    'FraudDetectionSettings',
    'AISettings',
    'MLModelTrainingSettings',
    'DataObservabilitySettings',
    'ModelPerformanceMonitoringSettings',
    'AdvancedRulesEngineSettings',
    'GNNServiceSettings',
    'MLDataPipelineSettings',
    'DataLineageSettings',
    'FeatureVectorSettings',
    'MLServiceSettings',
    'PredictiveRiskForecastingSettings',
    'AzureSettings',
    'TimeSeriesBehavioralSettings',
    'GPTFineTuningSettings',
    'RAGKnowledgeBaseSettings',
    'AdvancedAnalyticsSettings',
    'ExternalIntegrationSettings',
    'ExternalSystemSettings',
    'WebhookSubscriptionSettings',
    'SerilogSettings',
    'ExplainabilityServiceSettings',
    'OpenTelemetrySettings',
    'JaegerSettings',
    'PerformanceSettings',
    # Security Components
    'SecurityMiddleware',
    'JWTService',
    'PasswordService',
    'AuthenticationService',
    'AuthorizationService',
    'get_current_user',
    'require_auth',
    'SecuritySettings',
    'UserRole',
    'Permission',
    'UserContext',
    'LoginRequest',
    'LoginResponse',
    'RefreshTokenRequest',
    'LogoutRequest',
    'UserInfo',
    'JWTPayload',
    'AuthorizationPolicy',
    'SecurityAuditLog',
    'DeviceInfo',
    'SessionInfo',
    'ApiKeyInfo',
    'SecurityMetrics',
    # Performance Components
    'PerformanceMonitor',
    'PerformanceOptimizer',
    'performance_monitor',
    'performance_monitor_instance',
    'performance_optimizer',
    'PerformanceMetrics',
    'SystemMetrics',
    'PerformanceSummary',
    'PerformanceOptimizationRequest',
    'PerformanceOptimizationResponse',
    'PerformanceTestRequest',
    'PerformanceTestResponse',
    'PerformanceAlert',
    'PerformanceReport',
    'PerformanceConfiguration',
    # Database Components
    'DatabaseService',
    'database_service',
    # Data Quality Components
    'DataQualityService',
    'data_quality_service',
    # ML Training Components
    'MLTrainingPipeline',
    'ml_training_pipeline',
    # Feature Engineering Components
    'FeatureEngineeringService',
    'feature_engineering_service',
    # Rules Engine Components
    'AdvancedRulesEngine',
    'RuleManagementService',
    'rules_engine',
    'IRule',
    'get_default_static_rules',
    'RuleOperator',
    'RuleActionType',
    'RuleCondition',
    'RuleAction',
    'DynamicRule',
    'RuleResult',
    'RuleEvaluationResult',
    'RuleManagementRequest',
    'RuleManagementResponse',
    'RuleStatistics',
    'RuleTemplate',
    'RuleValidationResult',
    'RuleTestResult',
    # Messaging Components
    'MessagingService',
    'get_messaging_service',
    'ServiceBusPublisher',
    'ServiceBusSubscriber',
    'EventHubsPublisher',
    'MessagingStatus',
    'MessageStatus',
    'MessagingResult',
    'BatchMessagingResult',
    'MessagingHealthStatus',
    'MessagingMetrics',
    'MessagingConfiguration',
    'ServiceBusConfiguration',
    'EventHubsConfiguration',
    'RetryConfiguration',
    'DeadLetterQueueConfiguration',
    'FraudAlertMessage',
    'TransactionMessage',
    'MessageEnvelope',
    'MessageProcessingResult',
    'SubscriptionInfo',
    'EventHubInfo',
    'MessagingStats',
    # Customer Portal Components
    'CustomerPortalService',
    'customer_portal_service',
    'CaseStatus',
    'CasePriority',
    'CaseType',
    'ContactPreference',
    'FraudCase',
    'FraudCaseNote',
    'FraudReport',
    'FraudAlert',
    'SuspiciousTransaction',
    'CaseResolution',
    'CustomerProfile',
    'CaseStatistics',
    'PortalNotification',
    'CaseSearchCriteria',
    'CaseUpdateRequest',
    'CaseCreationRequest'
]
